required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 191
  y: 84
  z: -400
  yaw: -101
  pitch: 4.6
arenas:
  0:
    world: 'arena1'
    x: 25.564
    y: 159
    z: 31.528
    yaw: 175.5
    pitch: -1.6
  1:
    world: 'arena2'
    x: -0.504
    y: 67
    z: -0.416
    yaw: 2.2
    pitch: -3.2